spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20000323
    url: jdbc:mysql://localhost:3306/mybatisplus-test
server:
  port: 8080
